In [3]:
import pandas as pd 
import numpy as np

In [4]:
pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN
...,...,...,...,...,...
38395,Zimbabwe,ZWE,2096,NaN,100752.0
38396,Zimbabwe,ZWE,2097,NaN,91796.0
38397,Zimbabwe,ZWE,2098,NaN,87605.0
38398,Zimbabwe,ZWE,2099,NaN,76670.0
38399,Zimbabwe,ZWE,2100,NaN,70019.0

In [5]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy-hmd-unwpp.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy-hmd-unwpp.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [6]:
df.head(3)

        entity code  year  life_expectancy__sex_total__age_0__type_period
0  Afghanistan  AFG  1950                                         28.1563
1  Afghanistan  AFG  1951                                         28.5836
2  Afghanistan  AFG  1952                                         29.0138

In [7]:
df.loc[df["code"].isnull()]

,entity,code,year,life_expectancy__sex_total__age_0__type_period
370,Americas,NaN,1950,56.5028
371,Americas,NaN,1951,56.9204
372,Americas,NaN,1952,57.4020
373,Americas,NaN,1953,57.9060
374,Americas,NaN,1954,58.6525
...,...,...,...,...
17183,Small Island Developing States (SIDS),NaN,2019,72.0847
17184,Small Island Developing States (SIDS),NaN,2020,71.7761
17185,Small Island Developing States (SIDS),NaN,2021,69.8938
17186,Small Island Developing States (SIDS),NaN,2022,72.1257
17187,Small Island Developing States (SIDS),NaN,2023,72.7255

In [8]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

entity                                            0
code                                              0
year                                              0
life_expectancy__sex_total__age_0__type_period    0
dtype: int64

In [9]:
df = pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

In [10]:
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [12]:
df.shape

(38400, 5)

In [13]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [14]:
import sys

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.13.15 (tags/v3.13.15:4061bc4, Aug  5 2026, 13:05:39) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.5
NumPy: 2.5.2

In [15]:
df[df['Entity'] == 'Mexico']

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22200,Mexico,MEX,1951,732546.0,NaN
22201,Mexico,MEX,1952,769686.0,NaN
22202,Mexico,MEX,1953,809069.0,NaN
22203,Mexico,MEX,1954,853770.0,NaN
22204,Mexico,MEX,1955,897588.0,NaN
...,...,...,...,...,...
22345,Mexico,MEX,2096,NaN,-743957.0
22346,Mexico,MEX,2097,NaN,-748746.0
22347,Mexico,MEX,2098,NaN,-752676.0
22348,Mexico,MEX,2099,NaN,-755662.0
22349,Mexico,MEX,2100,NaN,-758552.0

In [16]:
df_extration_filas = df[df["Year"]==2020]
df_extration_filas

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN
519,Algeria,DZA,2020,747543.0,NaN
669,American Samoa,ASM,2020,-451.0,NaN
...,...,...,...,...,...
37719,Western Sahara,ESH,2020,10924.0,NaN
37869,World,OWID_WRL,2020,75707590.0,NaN
38019,Yemen,YEM,2020,1023451.0,NaN
38169,Zambia,ZMB,2020,545555.0,NaN
38319,Zimbabwe,ZWE,2020,255510.0,NaN

In [17]:
df_2006_2020_mex = df[(df["Entity"] == "Mexico") & (df["Year"]>=2006) & (df["Year"]<=2020)]
df_extraction_range = df_2006_2020_mex[["Entity", "Year", "Annual change in population"]]
df_extraction_range

       Entity  Year  Annual change in population
22255  Mexico  2006                    1442162.0
22256  Mexico  2007                    1520690.0
22257  Mexico  2008                    1599930.0
22258  Mexico  2009                    1625434.0
22259  Mexico  2010                    1624178.0
22260  Mexico  2011                    1619605.0
22261  Mexico  2012                    1574705.0
22262  Mexico  2013                    1525364.0
22263  Mexico  2014                    1440693.0
22264  Mexico  2015                    1288045.0
22265  Mexico  2016                    1179034.0
22266  Mexico  2017                    1148708.0
22267  Mexico  2018                    1173661.0
22268  Mexico  2019                    1189265.0
22269  Mexico  2020                    1036075.0

In [18]:
df_new = df[["Entity"]]
df_new

            Entity
0      Afghanistan
1      Afghanistan
2      Afghanistan
3      Afghanistan
4      Afghanistan
...            ...
38395     Zimbabwe
38396     Zimbabwe
38397     Zimbabwe
38398     Zimbabwe
38399     Zimbabwe

[38400 rows x 1 columns]

In [19]:
df.loc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [20]:
df.loc[:,["Entity","Year","Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [21]:
ds_apellido = df.loc[(df["Entity"]=="Morocco") & (df["Year"]>=2006) & (df["Year"]<=2023)]
ds_apellido

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
23455,Morocco,MAR,2006,413034.0,NaN
23456,Morocco,MAR,2007,415289.0,NaN
23457,Morocco,MAR,2008,420301.0,NaN
23458,Morocco,MAR,2009,424010.0,NaN
23459,Morocco,MAR,2010,436230.0,NaN
23460,Morocco,MAR,2011,445576.0,NaN
23461,Morocco,MAR,2012,442661.0,NaN
23462,Morocco,MAR,2013,432327.0,NaN
23463,Morocco,MAR,2014,417211.0,NaN
23464,Morocco,MAR,2015,402806.0,NaN
23465,Morocco,MAR,2016,415869.0,NaN
23466,Morocco,MAR,2017,422936.0,NaN
23467,Morocco,MAR,2018,393365.0,NaN
23468,Morocco,MAR,2019,371147.0,NaN
23469,Morocco,MAR,2020,373301.0,NaN
23470,Morocco,MAR,2021,370235.0,NaN
23471,Morocco,MAR,2022,374625.0,NaN
23472,Morocco,MAR,2023,383448.0,NaN

In [22]:
print(f"Media:  {ds_apellido["Annual change in population"].mean()}")
print(f"Mediana:  {ds_apellido["Annual change in population"].median()}")
print(f"Desviación estándar:  {ds_apellido["Annual change in population"].std()}")
print(f"Mínimo:  {ds_apellido["Annual change in population"].min()}")
print(f"Máximo:  {ds_apellido["Annual change in population"].max()}")

Media:  408576.1666666667
Mediana:  415579.0
Desviación estándar:  25203.01788943725
Mínimo:  370235.0
Máximo:  445576.0