In [1]:
import pandas as pd 
import numpy as np

In [2]:
pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN
...,...,...,...,...,...
38395,Zimbabwe,ZWE,2096,NaN,100752.0
38396,Zimbabwe,ZWE,2097,NaN,91796.0
38397,Zimbabwe,ZWE,2098,NaN,87605.0
38398,Zimbabwe,ZWE,2099,NaN,76670.0
38399,Zimbabwe,ZWE,2100,NaN,70019.0

In [3]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy-hmd-unwpp.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy-hmd-unwpp.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [5]:
df.head(3)

        entity code  year  life_expectancy__sex_total__age_0__type_period
0  Afghanistan  AFG  1950                                         28.1563
1  Afghanistan  AFG  1951                                         28.5836
2  Afghanistan  AFG  1952                                         29.0138

In [6]:
df.loc[df["code"].isnull()]

,entity,code,year,life_expectancy__sex_total__age_0__type_period
370,Americas,NaN,1950,56.5028
371,Americas,NaN,1951,56.9204
372,Americas,NaN,1952,57.4020
373,Americas,NaN,1953,57.9060
374,Americas,NaN,1954,58.6525
...,...,...,...,...
17183,Small Island Developing States (SIDS),NaN,2019,72.0847
17184,Small Island Developing States (SIDS),NaN,2020,71.7761
17185,Small Island Developing States (SIDS),NaN,2021,69.8938
17186,Small Island Developing States (SIDS),NaN,2022,72.1257
17187,Small Island Developing States (SIDS),NaN,2023,72.7255

In [7]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

entity                                            0
code                                              0
year                                              0
life_expectancy__sex_total__age_0__type_period    0
dtype: int64